# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 寝ていたい
email: myomotodq2@gmail.com
description: 主にゲームのことについてtwitterに書ききれなかったりやった記録を残しておきたいときに使う何か。
  もうずっと寝ていたい。
baseurl: "/wanto-sleep" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: myomoto_dq2
github_username:  myo-yo
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
